# Generated by Django 4.0.2 on 2022-02-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='BlogApp', max_length=255),
        ),
    ]
