# Generated by Django 4.0.2 on 2022-03-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_category_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
