# Generated by Django 4.0.2 on 2022-03-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0017_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
    ]
