# Generated by Django 4.0.2 on 2022-03-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0019_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_pic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.profile'),
        ),
    ]
