# Generated by Django 4.0.2 on 2022-03-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0022_alter_comment_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='profile_pic',
            new_name='user',
        ),
    ]
