# Generated by Django 4.0.2 on 2022-03-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0023_rename_profile_pic_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.TextField(null=True),
        ),
    ]
