# Generated by Django 4.0.2 on 2022-03-25 20:33

from django.db import migrations, models
import myblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0028_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=myblog.models.user_directory_path),
        ),
    ]
